=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-XSD_materiales2_RMD/okej4/ej4.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="publication" type="tipoPublication"/>

    <xs:complexType name="tipoPublication">
        <xs:sequence>
            <xs:element name="article" type="tipoArticle" maxOccurs="unbounded"/>
            <xs:element name="book" type="tipoBook" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoArticle">
        <xs:group ref="elementosArticulo"/>
        <xs:attributeGroup ref="atributosArticulo"/>
    </xs:complexType>

    <xs:complexType name="tipoBook">
        <xs:group ref="elementosLibro"/>
        <xs:attributeGroup ref="atributosLibro"/>
    </xs:complexType>

    <xs:simpleType name="tipoGenre">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Mystery"/>
            <xs:enumeration value="Drama"/>
            <xs:enumeration value="Fantasy"/>
            <xs:enumeration value="Terror"/>
            <xs:enumeration value="Comedy"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoEdition">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:group name="elementosArticulo">
        <xs:sequence>
            <xs:element name="headline" minOccurs="1" type="xs:string"/>
            <xs:element name="lead" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="body" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="notes" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="atributosArticulo">
        <xs:attribute name="author" use="required" type="xs:string"/>
        <xs:attribute name="date" type="xs:date"/>
    </xs:attributeGroup>

    <xs:group name="elementosLibro">
        <xs:sequence>
            <xs:element name="headline" minOccurs="1" type="xs:string"/>
            <xs:element name="lead" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
            <xs:element name="isbn" minOccurs="1" type="xs:string"/>
            <xs:element name="genre" minOccurs="1" type="tipoGenre"/>
        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="atributosLibro">
        <xs:attribute name="author" use="required" type="xs:string"/>
        <xs:attribute name="edition" use="required" type="tipoEdition"/>
        <xs:attribute name="date" type="xs:date"/>
    </xs:attributeGroup>
</xs:schema>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-XSD_materiales2_RMD/okej4/ej4.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<publication xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ej4.xsd"> 
    <article author="kelvin" date="2009-09-09"> 
        <headline>Apple's next big thing is Steve Jobs</headline> 
        <body>On September 9, Steve Jobs returned to the public eye ...</body> 
        <notes>Excellent analysis</notes> 
        <notes>Insightful</notes> 
    </article> 
    <article author="tim" date="2000-01-07"> 
        <headline>Exciting Announcement from Apple</headline> 
        <lead>This is a groundbreaking development...</lead> 
        <body>Read on for the full story</body> 
    </article> 
    <book author="peter" edition="2" date="2022-12-07">
        <headline>The Mystery of the Lost Key</headline>
        <lead>A thrilling adventure awaits...</lead> 
        <isbn>978-3-16-148410-0</isbn>
        <genre>Mystery</genre>
    </book>
</publication>
