<?xml version="1.0" encoding="UTF-8"?> 

<!-- Mensajes contiene más de un mensaje, mensaje no está declarado. Texto no está declarado correctamente. -->
<!DOCTYPE mensajes [ 
  <!ELEMENT mensajes (mensaje+)> 
	<!ELEMENT mensaje (de, para, hora, texto)>
	  <!ELEMENT de (#PCDATA)> 
	  <!ELEMENT para (#PCDATA)> 
	  <!ELEMENT hora (#PCDATA)> 
	  <!ELEMENT texto (#PCDATA | strong)*> 
	    <!ELEMENT strong (#PCDATA)> 
]> 
 
<mensajes> 
  <mensaje> 
    <de>Pepe (pepe@example.com)</de> 
    <para>Juan (juan@example.com)</para> 
    <hora>28/01/2021 17:48:23,61</hora> 
    <texto>¿Hola, Juan, qué haces?</texto> 
  </mensaje> 
  <mensaje> 
    <de>Juan (juan@example.com)</de> 
    <para>Pepe (pepe@example.com)</para> 
    <hora>28/01/2021 17:54:20,87</hora> 
    <texto>Aquí, aprendiendo <strong>XML</strong></texto> 
  </mensaje> 
</mensajes> 