<?xml version="1.0" encoding="UTF-8"?>

<!-- Contabilidad está mal declarado y apunte no está declarado. Ingreso y gasto no están declarados. -->
<!DOCTYPE contabilidad [ 
  <!ELEMENT contabilidad (apunte+)>	
	<!ELEMENT apunte ((ingreso | gasto), fecha, cantidad, concepto)> 
		<!ELEMENT ingreso EMPTY>
		<!ELEMENT gasto EMPTY>
		<!ELEMENT fecha (#PCDATA)> 
		<!ELEMENT cantidad (#PCDATA)> 
		<!ELEMENT concepto (#PCDATA)> 
]> 
<contabilidad> 
  <apunte> 
    <ingreso /> 
    <fecha>24 de febrero</fecha> 
    <cantidad>1800,00 €</cantidad> 
    <concepto>Salario</concepto> 
  </apunte> 
  <apunte> 
    <gasto /> 
    <fecha>28 de febrero</fecha> 
    <cantidad>74,25 €</cantidad> 
    <concepto>Recibo luz</concepto> 
  </apunte> 
</contabilidad> 