<?xml version="1.0" encoding="UTF-8"?> 

<!-- cerrado está declarado como elemento de aeropuerto, cuando no figura en el xml -->
<!DOCTYPE aeropuertos [ 
  <!ELEMENT aeropuertos (aeropuerto*)> 
  <!ELEMENT aeropuerto (nombre)> 
  <!ELEMENT nombre (#PCDATA)> 
]> 

<aeropuertos> 
  <aeropuerto> 
    <nombre>Berlín Schönefeld (SFX)</nombre> 
  </aeropuerto> 
  <aeropuerto> 
    <nombre>Berlín Tempelhof (THF)</nombre> 
  </aeropuerto> 
</aeropuertos> 