=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-DTD_materiales_RMD/okej21/ej21.dtd
<!ENTITY % UP "unidadDeProduccion (1|2|3) #REQUIRED">
    <!ELEMENT empresa (empleados, maquinaria)>
        <!ELEMENT empleados (empleado+)>
            <!ELEMENT empleado (nombre, apellidos)>
            <!ATTLIST empleado 
                %UP;
                categoria (mantenimiento|limpieza|produccion) #REQUIRED>
                <!ELEMENT nombre (#PCDATA)>
                <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT maquinaria (modelo+)>
            <!ELEMENT modelo (#PCDATA)>
            <!ATTLIST modelo
                %UP;
                tipo (A|B|C) #REQUIRED>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-DTD_materiales_RMD/okej21/ej21.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "ej21.dtd">
<empresa>
    <empleados>
        <empleado unidadDeProduccion="1" categoria="mantenimiento">
            <nombre>Juan</nombre>
            <apellidos>Pérez Rodriguez Delgado</apellidos>
        </empleado>
        <empleado unidadDeProduccion="2" categoria="limpieza">
            <nombre>Carlos</nombre>
            <apellidos>Pérez Rodriguez Delgado</apellidos>
        </empleado>
        <empleado unidadDeProduccion="3" categoria="produccion">
            <nombre>José</nombre>
            <apellidos>Pérez Rodriguez Delgado</apellidos>
        </empleado>
    </empleados>
    <maquinaria>
        <modelo unidadDeProduccion="1" tipo="A">J-KEE Cortadora de perfil</modelo>
        <modelo unidadDeProduccion="2" tipo="B">J-KEE Cortadora de perfil</modelo>
        <modelo unidadDeProduccion="3" tipo="C">J-KEE Cortadora de perfil</modelo>   
    </maquinaria>
</empresa>
