<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE escritores [ 
  <!ELEMENT escritores (escritor*)> 
  <!ELEMENT escritor (nombre, nacimiento)> 
  <!ELEMENT nombre (#PCDATA)> 
  <!ELEMENT nacimiento (#PCDATA)> 
]> 
 <!-- Los elementos del escitor deben respetar el orden -->

<escritores> 
  <escritor> 
    <nombre>Mario Vargas LLosa</nombre> 
    <nacimiento>28 de marzo de 1936</nacimiento> 
  </escritor> 
  <escritor> 
    <nombre>Milan Kundera</nombre> 
    <nacimiento>1 de abril de 1929</nacimiento> 
  </escritor> 
</escritores> 