=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejemplos/XSDejemplosGruposyRef/xmlElementosComplejosSinGrupos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clase" type="tipoClase"/>

    <xs:complexType name="tipoClase">
        <xs:sequence>
            <xs:element name="alumno" type="datos" maxOccurs="unbounded"/>
            <xs:element name="profesor" type="datos" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
        
    <xs:complexType name="datos">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="edad" type="xs:nonNegativeInteger"/>
            <xs:element name="direccion" type="xs:string"/>
            <xs:element name="cp" type="codigoPostal"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="codigoPostal">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejemplos/XSDejemplosGruposyRef/xmlElementosComplejosSinGrupos.xml
<?xml version="1.0" encoding="UTF-8"?>
<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xmlElementosComplejosSinGrupos.xsd">
    <alumno id="a102">
        <nombre>Juan</nombre>
        <edad>20</edad>
        <direccion>C/La Puebla 34</direccion>
        <cp>09001</cp> 
    </alumno>
    <alumno id="a103">
        <nombre>Laura</nombre>
        <edad>33</edad>
        <direccion>C/La San Juan 24</direccion>
        <cp>09003</cp>  
    </alumno>
    <profesor id="p045">
        <nombre>Juan</nombre>
        <edad>20</edad>
        <direccion>C/La Silos 66</direccion>
        <cp>09002</cp>
        <!--<asignatura>LM</asignatura>
        <asignatura>Prog</asignatura>-->
    </profesor>
</clase>
<!-- ¿qué pasa si quiero añadir un elemento más a profesor?
    Pero no quiero que lo tenga alumno.
Por ejemplo: asignaturas-->
