=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-XSD_materiales1_RMD/okej13/ej13.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lectura" type="tipoLectura"/>
    <xs:complexType name="tipoLectura">
        <xs:sequence>
            <xs:element name="libros" type="tipoLibros" minOccurs="1"/>
            <xs:element name="revistas" type="tipoRevistas" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoLibros">
        <xs:sequence>
            <xs:element name="libro" type="tipoLibro" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoLibro">
        <xs:choice>
            <xs:element name="novela" type="xs:string"/>
            <xs:element name="poesia" type="xs:string"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="tipoRevistas">
        <xs:sequence>
            <xs:element name="revista">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombreRevista" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
</xs:schema>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-XSD_materiales1_RMD/okej13/ej13.xml
<?xml version="1.0" encoding="UTF-8"?>
<lectura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ej13.xsd">
	<libros>
		<libro>
			<novela>Los pilares de la tierra</novela>
		</libro>
		<libro>
			<poesia>100 poemas de amor y una cancion desesperada</poesia>
		</libro>
	</libros>
	<revistas>
		<revista>
			<nombreRevista>PCWorld</nombreRevista>
		</revista>	
	</revistas>
</lectura>
