=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-XSD_materiales2_RMD/okej2/ej2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria" type="tipoLibreria"/>
        <xs:complexType name="tipoLibreria">
            <xs:sequence>
                <xs:element name="codigo" type="xs:string"/>
                <xs:element name="direccion" type="xs:string"/>
                <xs:element name="telefono">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="8"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="propietario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="libro" type="tipoLibro" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="tipoLibro">
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="autores" type="tipoAutores"/>
                <xs:element name="formato" type="tipoFormato"/>
                <xs:element name="publicacion" type="xs:gYear"/>
                <xs:element name="precio" type="tipoPrecio"/>
            </xs:sequence>
            <xs:attribute name="codigo" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="c\d{3}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>

        <xs:complexType name="tipoAutores" mixed="true">
            <xs:sequence>
                <xs:element name="autor" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:complexType name="tipoPrecio">
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="oferta" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>

        <xs:simpleType name="tipoFormato">
            <xs:restriction base="xs:string">
                <xs:enumeration value="bolsillo"/>
                <xs:enumeration value="tapa blanda"/>
                <xs:enumeration value="tapa dura"/>
                <xs:enumeration value="rÃºstica"/>
            </xs:restriction>
        </xs:simpleType>     
</xs:schema>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-XSD_materiales2_RMD/okej2/ej2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ej2.xsd">
	<codigo>1263</codigo>
	<direccion>C/ Juan de Juni 31</direccion>
	<telefono>98355555</telefono>
	<propietario>
		<nombre>Juanito</nombre>
	</propietario>
	<libro codigo="c111">
		<titulo> Cien años de soledad </titulo>
		<autores> Gabriel García Márquez </autores>
		<formato>tapa blanda</formato>
		<publicacion>1967</publicacion>
		<precio oferta="si">23.5</precio>
	</libro>
	<libro codigo="c222">
		<titulo> Cocina de autor </titulo>
		<autores> 
			<autor>Pedro Pérez Pintor</autor>
			<autor>Ana Alvarez Alba</autor>
		</autores>
		<formato>bolsillo</formato>
		<publicacion>2020</publicacion>
		<precio>20</precio>
	</libro>
</libreria>
