=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-DTD_materiales_RMD/okej7/ej7.dtd
<!ELEMENT libreria (codigo+, direccion+, telefono+, propietario+,libro+)>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT propietario (nombre+, telefonopro*)>
        <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT libro (titulo, autores?, formato, publicacion, precio, cantidad?)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT autores (#PCDATA | autor)*>
            <!ELEMENT autor (#PCDATA)>
        <!ELEMENT formato (#PCDATA)>
        <!ELEMENT publicacion (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-DTD_materiales_RMD/okej7/ej7.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE libreria SYSTEM "ej7.dtd">
<libreria>
	<codigo>1263</codigo>
	<direccion>C/ Juan de Juni 31</direccion>
	<telefono>983555555</telefono>
	<propietario>
		<nombre>Juanito</nombre>
	</propietario>
	<libro>
		<titulo> Cien años de soledad </titulo>
		<autores> Gabriel García Márquez </autores>
		<formato> Rústica </formato>
		<publicacion>1967 </publicacion>
		<precio>23,5</precio>
	</libro>
	<libro>
		<titulo> Cocina de autor </titulo>
		<autores> 
			<autor>Pedro Pérez Pintor</autor>
			<autor>Ana Alvarez Alba</autor>
		</autores>
		<formato> Bolsillo </formato>
		<publicacion>2020 </publicacion>
		<precio>20</precio>
	</libro>
</libreria>
