=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-DTD_materiales_RMD/okej8/ej8.dtd
<!ELEMENT menu (denominacion, precio, fecha?, plato*, bebida)>
    <!ELEMENT denominacion (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT plato (entrantes | primero | postre)>
        <!ELEMENT entrantes (#PCDATA)>
        <!ELEMENT primero (#PCDATA)>
        <!ELEMENT postre (#PCDATA)>
    <!ELEMENT bebida EMPTY>

=== rodrigomardel/Desarrollo-de-Aplicaciones-Web/1-Lenguaje_de_marcas/UT6_DTD-XSD/ejercicios/UT6-DTD_materiales_RMD/okej8/ej8.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE menu SYSTEM "ej8.dtd">
<menu>
	<denominacion> Menu del d√≠a</denominacion>
	<precio>8,50</precio>
	<fecha>12/04/2010</fecha>
	<plato>
		<entrantes> Sepia a la plancha</entrantes>
	</plato>
	<plato>
		<primero>Lubina al horno</primero>
	</plato>
	<plato>
		<primero>Solomillo con patatas</primero>
	</plato>
	<plato>
		<postre> Flan con nata</postre>
	</plato>
	<bebida/>
</menu>
